### ISSUE TITLE
Upgrade Dependencies GSSDP and GUPnP

### ISSUE THREAD

**Issue by dfurmans** [stokito/upnp-router-control#2]
Status QUO
-------
GSSDP library ( >= 1.2 )
GUPnP library ( >= 1.2 )

DESC:
----
Info: runtime org.gnome.Platform branch 44 is end-of-life, with reason:
   The GNOME 44 runtime is no longer supported as of March 20, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:

TODO
---
Update both dependencies to version >= 1.6
Change code base sections which are required.

**Comment by stokito** [comment]
Hi @dfurmans this is a mirror from the GNOME's GitLab: https://gitlab.gnome.org/DnaX/upnp-router-control/-/tree/develop

So please create an issue there. I played with sources but didn't sent any PR

**Comment by dfurmans** [comment]
Okey! Got it. I have already seen that in GitLab: https://gitlab.gnome.org/DnaX/upnp-router-control/-/tree/develop is already up-to-date. So I am closing this issue.
